version: '3.9'

services:
  java_db:
    container_name: java_db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: <DATABASE_USERNAME>
      POSTGRES_PASSWORD: <DATABASE_PASSWORD>
      POSTGRES_DB: <DATABASE_DB>
  pgadmin_db:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4_container
    ports:
        - "8888:80"
    environment:
        PGADMIN_DEFAULT_EMAIL: <PGADMIN_DEFAULT_EMAIL>
        PGADMIN_DEFAULT_PASSWORD: <PGADMIN_PASSWORD>
    depends_on:
      - java_db
