version: '3.9'

services:
  # java_app:
  #   container_name: java_app
  #   build: 
  #     context: Simple-PostgresqlSpringDocker
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - DATABASE_URL=jdbc:postgresql://java_db:5432/demo
  #     - DATABASE_USERNAME=postgres
  #     - DATABASE_PASSWORD=postgres
  #   depends_on:
  #     - java_db
  #   image: <your-image>
  java_db:
    container_name: java_db
    image: postgres:15.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: demo
  pgadmin_db:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4_container
    ports:
        - "8888:80"
    environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - java_db
