version: '3.9'

services:
  java_app:
    container_name: java_app
    build: 
      context: Simple-PostgresqlSpringDocker
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=<DATABASE_URL>
      - DATABASE_USERNAME=<DATABASE_USERNAME>
      - DATABASE_PASSWORD=<DATABASE_PASSWORD>
      - JWT_SECRET=<JWT_SECRET_encoded_BASE64>
    depends_on:
      - java_db
    image: <your_dockerhub_username>/<your_image_name>:<your_tag>
  java_db:
    container_name: java_db
    image: postgres:15.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: <DATABASE_USERNAME>
      POSTGRES_PASSWORD: <DATABASE_PASSWORD>
      POSTGRES_DB: <DATABASE_DB>
  pgadmin_db:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4_container
    ports:
        - "8888:80"
    environment:
        PGADMIN_DEFAULT_EMAIL: <PGADMIN_DEFAULT_EMAIL>
        PGADMIN_DEFAULT_PASSWORD: <PGADMIN_PASSWORD>
    depends_on:
      - java_db
