spring:
  application:
    name: KSpringDocker
  graphql:
    graphiql:
          enabled: true
          path: /graphiql
  security:
    oauth2:
      resourceserver:
        jwt:
          # Using custom JWT encoder/decoder beans; issuer-uri can be provided to use external provider instead
          issuer-uri: ${ISSUER_URL:http://keycloak-admin:8181/realms/spring-template}
  datasource:
    url: ${DB_URL}
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-nano
          temperature: 0.7

server:
  port: 8080