apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
  labels:
    app: spring-boot
    service: java-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
        network: "true"
        service: java-app
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:latest
          command:
           - sh
           - -c
           - |-
             until nc -zv java-db 5432; do
               sleep 1
             done
      containers:
        - name: java-app
          image: <your-image>
          env:
           - name: DATABASE_PASSWORD
             valueFrom: 
               secretKeyRef:
                 name: secret-kb-values
                 key: DATABASE_PASSWORD
           - name: DATABASE_URL
             valueFrom:
               configMapKeyRef:
                 name: config-kub-values
                 key: DATABASE_URL
           - name: DATABASE_USERNAME
             valueFrom:
               configMapKeyRef:
                 name: config-kub-values
                 key: POSTGRES_USER
          ports:
          - containerPort: 8080
            hostPort: 0
            protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  name: java-app
  labels:
    app: spring-boot
spec:
  selector:
    app: java-app
  ports:
  - port: 8080
    targetPort: 8080
  type: LoadBalancer