apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pgadmin
    service: pgadmin
  name: pgadmin-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin-db
  template:
    metadata:
      labels:
        app: pgadmin-db
        network: "true"
        service: pgadmin-db
    spec:
      containers:
      - name: pgadmin-db
        image: dpage/pgadmin4:latest
        env:
          - name: PGADMIN_DEFAULT_EMAIL
            valueFrom:
              configMapKeyRef:
                name: config-kub-values
                key: PGADMIN_DEFAULT_EMAIL
          - name: PGADMIN_DEFAULT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret-kb-values
                key: PGADMIN_DEFAULT_PASSWORD
        ports:
          - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: pgadmin-db
  labels:
    app: pgadmin-db
spec:
  selector:
    app: pgadmin-db
  ports:
  - port: 80
    targetPort: 80
  type: NodePort