/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    id("io.freefair.lombok") version "8.6"
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.org.springframework.boot.spring.boot.starter.data.jpa)
    api(libs.org.springframework.boot.spring.boot.starter.web)
    api(libs.org.springdoc.springdoc.openapi.starter.webmvc.ui)
    api(libs.org.springdoc.springdoc.openapi.starter.webmvc.api)
    api(libs.io.jsonwebtoken.jjwt.api)
    api(libs.org.projectlombok.lombok)
    api(libs.org.springframework.boot.spring.boot.starter.security)
    runtimeOnly(libs.org.postgresql.postgresql)
    runtimeOnly(libs.io.jsonwebtoken.jjwt.jackson)
    runtimeOnly(libs.io.jsonwebtoken.jjwt.impl)
    testImplementation(libs.org.springframework.boot.spring.boot.starter.test)
}

group = "com.pee"
version = "2.0.0"
description = "dockerized.postgresql"
java.sourceCompatibility = JavaVersion.VERSION_21

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
