# Makefile for a Gradle-based project

# Default action if no arguments are given to make.
default: build

# Task aliases
build:
	./gradlew build

clean:
	./gradlew clean

# Define a .PHONY rule to tell make that these aren't actually files.
.PHONY: default build clean
