name: Java CI with Gradle

on:
  push:
    branches: [ "gradle-evo" ]
  pull_request:
    branches: [ "gradle-evo" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    # Removed duplicated Setup Gradle step, as it's unnecessary to have it twice before each Gradle build command.

    - name: Build with Gradle Wrapper
      run: ./gradlew build
      working-directory: ./Simple-PostgresqlSpringDocker
      # Ensures the command runs in the correct project directory
